name: docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - sphinx
  - sphinx-copybutton
  - sphinx-design
  - myst-nb
  - pip:
    - pytomoatt
    - sphinx-gallery
    - sphinxcontrib-bibtex
    - sphinx-icon
    - furo
